module.exports = Object.freeze({
    BLANK_LINE: ''.padEnd(40),
    TEXT_RED:		'\x01',
	TEXT_GREEN:		'\x02',
	TEXT_YELLOW:	'\x03',
	TEXT_BLUE:		'\x04',
	TEXT_MAGENTA: 	'\x05',
	TEXT_CYAN:		'\x06',
	TEXT_WHITE:		'\x07',
	FLASH_ON:		'\x08',
	FLASH_OFF:		'\x09',
	NORMAL_HEIGHT:	'\x0c',
	DOUBLE_HEIGHT:	'\x0d',
	GFX_RED:		'\x11',
	GFX_GREEN:		'\x12',
	GFX_YELLOW:		'\x13',
	GFX_BLUE:		'\x14',
	GFX_MAGENTA:	'\x15',
	GFX_CYAN:		'\x16',
	GFX_WHITE:		'\x17',
	CONCEAL:		'\x18',
	CONTIGUOUS_GFX:	'\x19',
	SEPARATED_GFX:	'\x1a',
	BLACK_BACKGRD:	'\x1b',
	NEW_BACKGRD:	'\x1d',
	HOLD_GFX:		'\x1e',
	RELEASE_GFX:	'\x1f'
});